- name: Upload file to S3 bucket
  hosts: localhost
  gather_facts: false
  vars:
    s3_bucket: "train-data-apoorva"
    source_file: "src/data_copy.csv"
    destination_file: "data.csv"

  tasks:
    - name: Upload file to S3 bucket
      amazon.aws.aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ destination_file }}"
        src: "{{ source_file }}"
        mode: "put"
